#ifndef CHASSIS_H_INCLUDED
#define CHASSIS_H_INCLUDED

#include <stdint.h>

enum CHASSIS_4W { WHEEL_4W_LF, WHEEL_4W_LR, WHEEL_4W_RF, WHEEL_4W_RR};
//enum CHASSIS_3W { WHEEL_3W_}
enum CHASSIS_2W { WHEEL_2W_LEFT, WHEEL_2W_RIGHT};
enum CHASSIS_ROTATION { CHASSIS_CW, CHASSIS_CCW};




#endif
